<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Configurations>Debug;Release;Testing</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NationalInstruments.Common">
      <HintPath>C:\Program Files (x86)\National Instruments\Measurement Studio\DotNET\v4.0\AnyCPU\NationalInstruments.Common 19.1.40\NationalInstruments.Common.dll</HintPath>
    </Reference>
    <Reference Include="NationalInstruments.DAQmx">
      <HintPath>C:\Program Files (x86)\National Instruments\MeasurementStudioVS2012\DotNET\Assemblies (64-bit)\Current\NationalInstruments.DAQmx.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Target Name="EnforceX64Only" BeforeTargets="Build">
	<Error Condition="'$(Platform)' != 'x64'" Text="Build halted! This project relies on unmanaged 64-bit DAQmx libraries and MUST be compiled as x64. Please switch your active platform in Configuration Manager." />
  </Target>
</Project>